name: IntegrationTests

on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]
    workflow_dispatch:

jobs:
    configure_and_build:
        runs-on: windows-2022
        steps:
        - uses: actions/checkout@v4
        
        - name: Setup cmake
          uses: jwlawson/actions-setup-cmake@v2
          with:
            cmake-version: '3.26.1'
        
        - name: Configure
          working-directory: ${{github.workspace}}/integration_test
          run: |
            mkdir _build
            cd _build
            cmake ..
          shell: cmd
        
        - name: Build
          working-directory: ${{github.workspace}}/integration_test/_build
          run: |
            cmake --build . --config Debug
          shell: cmd

    just_configure:
        runs-on: windows-2022
        strategy:
          matrix:
            folder: [ fetch_test ]
        steps:
        - uses: actions/checkout@v4
        
        - name: Setup cmake
          uses: jwlawson/actions-setup-cmake@v2
          with:
            cmake-version: '3.26.1'
        
        - name: Configure
          working-directory: ${{github.workspace}}/${{matrix.folder}}
          run: |
            mkdir _build
            cd _build
            cmake ..
          shell: cmd
